// <auto-generated />
namespace PROJECT._360.DATAACCESS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class hgf : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(hgf));
        
        string IMigrationMetadata.Id
        {
            get { return "202409261331159_hgf"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
