// <auto-generated />
namespace PROJECT._360.DATAACCESS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig45 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig45));
        
        string IMigrationMetadata.Id
        {
            get { return "202409241850019_mig45"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
