// <auto-generated />
namespace PROJECT._360.DATAACCESS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class chc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(chc));
        
        string IMigrationMetadata.Id
        {
            get { return "202409241451585_chc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
